version: "3.8"

services:
  api:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo 
    restart: always 
    ports:
      - "27017:27017"
